
package servicos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PessoaService", targetNamespace = "http://servicos/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PessoaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/pesquisarPessoaRequest", output = "http://servicos/PessoaService/pesquisarPessoaResponse")
    public RetornoSoap pesquisarPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        Pessoa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/alterarPessoaRequest", output = "http://servicos/PessoaService/alterarPessoaResponse")
    public RetornoSoap alterarPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        Pessoa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/recuperarPessoaRequest", output = "http://servicos/PessoaService/recuperarPessoaResponse")
    public RetornoSoap recuperarPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/removerPessoaRequest", output = "http://servicos/PessoaService/removerPessoaResponse")
    public RetornoSoap removerPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/inserirPessoaRequest", output = "http://servicos/PessoaService/inserirPessoaResponse")
    public RetornoSoap inserirPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        Pessoa arg0);

    /**
     * 
     * @return
     *     returns servicos.RetornoSoap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servicos/PessoaService/recuperarTodosRequest", output = "http://servicos/PessoaService/recuperarTodosResponse")
    public RetornoSoap recuperarTodos();

}
