
package servicos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PessoaServiceImplService", targetNamespace = "http://servicos/", wsdlLocation = "http://localhost:8085/AulaWebSevice/pessoas?wsdl")
public class PessoaServiceImplService
    extends Service
{

    private final static URL PESSOASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PESSOASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PESSOASERVICEIMPLSERVICE_QNAME = new QName("http://servicos/", "PessoaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/AulaWebSevice/pessoas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PESSOASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PESSOASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PessoaServiceImplService() {
        super(__getWsdlLocation(), PESSOASERVICEIMPLSERVICE_QNAME);
    }

    public PessoaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PESSOASERVICEIMPLSERVICE_QNAME, features);
    }

    public PessoaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PESSOASERVICEIMPLSERVICE_QNAME);
    }

    public PessoaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PESSOASERVICEIMPLSERVICE_QNAME, features);
    }

    public PessoaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PessoaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServiceImplPort")
    public PessoaService getPessoaServiceImplPort() {
        return super.getPort(new QName("http://servicos/", "PessoaServiceImplPort"), PessoaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServiceImplPort")
    public PessoaService getPessoaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos/", "PessoaServiceImplPort"), PessoaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PESSOASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PESSOASERVICEIMPLSERVICE_EXCEPTION;
        }
        return PESSOASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
